apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpd-demo-alejandra
  namespace: argocd-taller
spec:
  project: default
  source:
    repoURL: https://github.com/alexmunozcalderon/taller-httpd-release-engineering.git
    targetRevision: main
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-alejandra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
