apiVersion: v1
kind: Secret
metadata:
  name: github-auth
  annotations:
    tekton.dev/git-0: https://github.com
type: kubernetes.io/basic-auth
stringData:
  username: alexmunozcalderon
  password: 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
